### ISSUE TITLE
Mudança na estrutura dos arquivos dos hinos

### ISSUE THREAD

**Issue by PabloDinella** [coisasdoalto/hinarios.app#46]
Alguém me notificou que o hino 97 do HC falta um estribilho. Analisando o hino, me parece que teremos que alterar a estrutura do json dos hinos, para incluir o `chorus` dentro do array das `stanzas`, para poder ter mais de um `chorus` e podermos colocá-lo em qualquer posição. No caso do 97 o primeiro `chorus` seria:

> Aleluia ao Cordeiro que nos resgatou (bis)
E com o Seu sangue nos purificou!

após a primeira `stanza`, e o segundo `chorus` é:

> Aleluia! Já creio, já creio em Jesus (bis)
E salvação tenho no sangue da cruz! 

após a `stanza` 4.

Pode-se verificar isso neste vídeo do hino: https://www.youtube.com/watch?v=v9A-g5hbxCE

**Comment by raphaeldevs** [comment]
Resolvido em https://github.com/coisasdoalto/hinarios.app/pull/68
